const PDFPrewiewerStyles = (theme) => ({
  pdfPreviewer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.palette.background.default,
    boxShadow: theme.shadows[2],
  },
  canvasContainer: {
    width: "100%",
    height: "100%",
    overflow: "auto",
    display: "grid",
    placeItems: "center",
    position: "relative",
  },
  pdfToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px",
    backgroundColor: theme.palette.background.paper,
    boxShadow: theme.shadows[1],
    width: "100%",
    position: "relative",
  },
  navigationControls: {
    padding: "0px 2px",
    display: "flex",
    alignItems: "center",
    color: theme.palette.text.primary,
    position: "relative",
  },
  toolbarButton: {
    display: "flex",
    color: theme.palette.text.primary,
    alignItems: "center",
    padding: "0",
    minWidth: "auto",
    gap: "8px",
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
    },
  },
  modal: {
    zIndex: 1000,
    width: "100%",
    bgcolor: "transparent",
    position: "absolute",
    display: "flex",
    justifyContent: "center",
  },
  searchContainer: {
    display: "flex",
    flexWrap: "wrap",
    padding: "10px",
    alignItems: "center",
    backgroundColor: theme.palette.background.paper,
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    borderRadius: "4px",
    maxWidth: "600px",
    height: "fit-content",
    marginTop: "10px",
  },
  searchInput: {
    border: "1px solid #ccc",
    padding: "8px",
    display: "block",
    flex: "1",
    borderRadius: "4px",
    outline: "none",
  },
  searchButton: {
    marginLeft: "8px",
    padding: "4px 8px",
    backgroundColor: theme.palette.primary.main,
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: theme.palette.primary.dark,
    },
  },
  menuItem: {
    minHeight: "auto",
    padding: "0",
  },
  menuButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
    padding: "0",
    button: {
      padding: "6px 16px",
      width: "100%",
      height: "100%",
      justifyContent: "flex-start",
      color: theme.palette.text.primary,
    },
    svg: {
      marginRight: "8px",
      color: theme.palette.text.primary,
    },
  },
  divider: {
    margin: "0 !important",
  },
});

export default PDFPrewiewerStyles;
